{% set version = '1.0.7' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pre
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pre_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pre/pre_{{ version }}.tar.gz
  sha256: 6181ee561790398d90f4543f635115dfb8a85867061237edf4189a65a177139c

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-formula
    - r-matrix
    - r-matrixmodels
    - r-earth
    - r-glmnet
    - r-partykit >=1.2_0
    - r-rpart
    - r-stringr
    - r-survival
  run:
    - r-base
    - r-formula
    - r-matrix
    - r-matrixmodels
    - r-earth
    - r-glmnet
    - r-partykit >=1.2_0
    - r-rpart
    - r-stringr
    - r-survival

test:
  commands:
    - $R -e "library('pre')"           # [not win]
    - "\"%R%\" -e \"library('pre')\""  # [win]

about:
  home: https://github.com/marjoleinF/pre
  license: GPL-2.0-only and GPL-3.0-only
  summary: Derives prediction rule ensembles (PREs). Largely follows the procedure for deriving
    PREs as described in Friedman & Popescu (2008; <DOI:10.1214/07-AOAS148>), with adjustments
    and improvements. The main function pre() derives prediction rule ensembles consisting
    of rules and/or linear terms for continuous, binary, count, multinomial, and multivariate
    continuous responses. Function gpe() derives generalized prediction ensembles, consisting
    of rules, hinge and linear functions of the predictor variables.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# Package: pre
# Title: Prediction Rule Ensembles
# Version: 1.0.7
# Authors@R: c(person("Marjolein", "Fokkema", role = c("aut", "cre"), email = "m.fokkema@fsw.leidenuniv.nl"), person(given = "Benjamin", family = "Christoffersen", role = "aut", email = "boennecd@gmail.com"))
# Author: Marjolein Fokkema [aut, cre], Benjamin Christoffersen [aut]
# Maintainer: Marjolein Fokkema <m.fokkema@fsw.leidenuniv.nl>
# Description: Derives prediction rule ensembles (PREs). Largely follows the procedure for deriving PREs as described in Friedman & Popescu (2008; <DOI:10.1214/07-AOAS148>), with adjustments and improvements. The main function pre() derives prediction rule ensembles consisting of rules and/or linear terms for continuous, binary, count, multinomial, and multivariate continuous responses. Function gpe() derives generalized prediction ensembles, consisting of rules, hinge and linear functions of the predictor variables.
# URL: https://github.com/marjoleinF/pre
# BugReports: https://github.com/marjoleinF/pre/issues
# Depends: R (>= 3.5.0)
# Imports: earth, Formula, glmnet, graphics, methods, partykit (>= 1.2-0), rpart, stringr, survival, Matrix, MatrixModels
# Suggests: interp, datasets, doParallel, foreach, glmertree, grid, mlbench, testthat, mboost, ggplot2, caret, pROC, knitr, rmarkdown, mice, shape
# License: GPL-2 | GPL-3
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.2.3
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2024-01-12 15:44:17 UTC; fokkemam
# Repository: CRAN
# Date/Publication: 2024-01-12 19:30:02 UTC
